# Generated by Django 4.2.1 on 2023-05-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.CharField(blank=True, max_length=10)),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('insight', models.CharField(max_length=250)),
                ('url', models.URLField(max_length=250)),
                ('region', models.CharField(max_length=100)),
                ('start_year', models.CharField(blank=True, max_length=10)),
                ('impact', models.CharField(blank=True, max_length=100)),
                ('added', models.CharField(max_length=100)),
                ('published', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('likelihood', models.IntegerField()),
            ],
        ),
    ]
